name: ğŸ—ï¸ Build and publish to Github Container Registry

on:
    push:
        branches: [main, production, develop]
        tags: ['v*.*.*']
    pull_request:
        branches:
            - production
            - main
            - develop
    merge_group:
        branches:
            - production
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    lint:
        name: ğŸ” Formatting & Linting
        runs-on: ubuntu-latest
        steps:
            - name: â¬‡ï¸  Checkout repository
              uses: actions/checkout@v6.0.1
            - name: ğŸ”¨ Setup node
              uses: actions/setup-node@v6.2.0
              with:
                  node-version-file: '.nvmrc'
            - name: ğŸ“² Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Prettier
              run: npx prettier --check .

    test:
        name: ğŸ§ª Test
        runs-on: ubuntu-latest
        steps:
            - name: â¬‡ï¸  Checkout repository
              uses: actions/checkout@v6.0.1
            - name: ğŸ”¨ Setup node
              uses: actions/setup-node@v6.2.0
              with:
                  node-version-file: '.nvmrc'
            - name: ğŸ“² Install dependencies
              run: npm ci
            - name: Run unit tests
              run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

    build-and-push-image:
        name: ğŸ—ï¸ Build and publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: â¬‡ï¸  Checkout repository
              uses: actions/checkout@v6.0.1
              with:
                  fetch-tags: true
                  fetch-depth: 0

            - name: ğŸ”‘ Log in to the Container registry
              uses: docker/login-action@v3.6.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: ğŸ“‹ Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5.10.0
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  flavor: |
                      latest=auto
                      prefix=
                      suffix=

            - name: ğŸ—ï¸ Build and push Docker image
              if: github.ref != 'refs/heads/develop'
              uses: docker/build-push-action@v6.18.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
            - name: ğŸ—ï¸ Build and push Docker Staging image
              # Only build main images for Staging
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v6.18.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}-Staging
                  labels: ${{ steps.meta.outputs.labels }}-Staging
                  file: staging.Dockerfile
            - name: ğŸ—ï¸ Build and push Docker develop image
              # Only build develop images for Staging
              if: github.ref == 'refs/heads/develop'
              uses: docker/build-push-action@v6.18.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}-Develop
                  labels: ${{ steps.meta.outputs.labels }}-Develop
                  file: develop.Dockerfile
